### ISSUE TITLE
Illegal en passant

### ISSUE THREAD

**Issue by tttony** [differentprogramming/jacksprat#1]
Hi!

I was testing your engine 1000 games 1m + 1s vs Skiull with Arena 3.0 in Windows 7 x64

In the attached file you can see the 104 games where Jacksprat moved illegally as en passant according to the arena.debug, sorry the debug file it's huge but just open and search: 'illegal' and you can see some of the games (not all games are in the debug file) also there is one game that forfeit, search: 'forfeit'

I also think that there are anothers bugs there because your engine has many search and eval features that should make it strong, I think it should be like ~100/200 ELO+ than Skiull, Skiull is a very-very basic engine, deleting all illegal and forfeit games your engine is 20 ELO+

**Comment by tttony** [comment]
I can't edit and I don't know what happened with the attached file, here you can download 

https://www.mediafire.com/?7u8bx6ng69gys3l

**Comment by differentprogramming** [comment]
closed.
thanks for looking at it.
I think there's still a bug with recognizing that the other player has underpromoted, but I found it yet.
